wordpress:
  image: wordpress
  links:
    - wordpress_db:mysql
  ports:
    - 8080:80
  volumes:
    - ./wp-content/themes:/var/www/html/wp-content/themes   
wordpress_db:
  image: mariadb
  environment:
    MYSQL_ROOT_PASSWORD: examplepass
  volumes:
    - db_data:/var/lib/mysql